import { MemoryRouter, Route, Routes } from 'react-router-dom';
import { renderToStaticMarkup } from 'react-dom/server';
import { describe, expect, it } from 'vitest';
import AiLabEntryPage from './AiLabEntryPage';

function renderEntry(entryId = 'designing-an-end-to-end-product-prototype-with-ai') {
  return renderToStaticMarkup(
    <MemoryRouter initialEntries={[`/ai-lab/${entryId}`]}>
      <Routes>
        <Route path="/ai-lab/:entryId" element={<AiLabEntryPage />} />
      </Routes>
    </MemoryRouter>,
  );
}

describe('AiLabEntryPage', () => {
  it('renders the richer end-to-end experiment media sections', () => {
    const markup = renderEntry();

    expect(markup).toContain('>06<');
    expect(markup).toContain('Generating UI in Stitch and Figma Make');
    expect(markup).toContain('Testing brand fidelity');
    expect(markup).toContain('Turning designs into prototypes');

    expect(markup).toContain(
      'alt="Workflow diagram showing the experiment from product definition through prototype generation."',
    );
    expect(markup).toContain(
      'alt="Research board capturing task flows and prioritised requirements for the travel-concierge concept."',
    );
    expect(markup).toContain(
      'alt="Comparison board showing the PRDs generated by GPT-5.4, Gemini, and Claude."',
    );

    expect(markup).toContain('Website reference only');
    expect(markup).toContain('Generic design.md');
    expect(markup).toContain('Your own design system design.md');

    expect(markup).toContain('OpenAI prototype');
    expect(markup).toContain('Claude prototype');
    expect(markup).toContain('Gemini prototype');

    expect(markup.match(/<video/g)).toHaveLength(4);
  });
});
